version: '3'
  
services:
    swzpln:
        container_name: swzpln-alpha
        image: php:apache
        expose:
            - 80
        volumes:
            - ./html:/var/www/html
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: alpha.swzpln.de,alpha.opencityplans.com
            LETSENCRYPT_HOST: alpha.swzpln.de,alpha.opencityplans.com

networks:
  default:
    external:
      name: nginx-proxy
