version: '3'
  
services:  
    swzpln:
        container_name: swzpln
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
        restart: unless-stopped
