version: '3'
  
services:
    swzpln:
        container_name: swzpln
        image: php:apache
        expose:
            - 80
        volumes:
            - ./html:/var/www/html
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: swzpln.de,www.swzpln.de
            LETSENCRYPT_HOST: swzpln.de,www.swzpln.de

networks:
  default:
    external:
      name: nginx-proxy