version: '3'
  
services:
    swzpln:
        container_name: swzpln
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 80
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: swzpln.de,www.swzpln.de,opencityplans.com,www.opencityplans.com
            LETSENCRYPT_HOST: swzpln.de,www.swzpln.de,opencityplans.com,www.opencityplans.com

networks:
  default:
    external:
      name: nginx-proxy
