version: '3'
  
services:
    swzpln:
        container_name: swzplnde
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 80
        volumes:
            - ./html/c/db:/var/www/html/c/db
        restart: unless-stopped
        environment:
            OPENTOPODATA_API_KEY: ${OPENTOPODATA_API_KEY}

networks:
  default:
    name: caddy
    external: true
