import { describe, it, expect } from 'vitest';
import { exportToOBJ } from './obj';
import type { GeometryObject, Bounds } from '../types';

const testBounds: Bounds = {
	north: 48.8,
	south: 48.7,
	east: 9.2,
	west: 9.1
};

function makeBuilding(): GeometryObject {
	return {
		type: 'building',
		path: [
			{ x: 10, y: 10 },
			{ x: 20, y: 10 },
			{ x: 20, y: 20 },
			{ x: 10, y: 20 }
		],
		buildingMetadata: { height: 10, levels: 3 }
	};
}

function decodeOBJ(result: Uint8Array): string {
	return new TextDecoder().decode(result);
}

describe('OBJ exporter', () => {
	it('should return a Uint8Array', async () => {
		const result = await exportToOBJ([], null, testBounds);
		expect(result).toBeInstanceOf(Uint8Array);
		expect(result.length).toBeGreaterThan(0);
	});

	it('should contain OBJ header comments', async () => {
		const result = await exportToOBJ([], null, testBounds);
		const obj = decodeOBJ(result);
		expect(obj).toContain('# OBJ File Generated by swzpln');
		expect(obj).toContain('swzpln.de');
	});

	it('should contain attribution', async () => {
		const result = await exportToOBJ([], null, testBounds);
		const obj = decodeOBJ(result);
		expect(obj).toContain('OpenStreetMap');
	});

	it('should contain vertex data for buildings', async () => {
		const result = await exportToOBJ([makeBuilding()], null, testBounds);
		const obj = decodeOBJ(result);
		// Vertices start with 'v '
		expect(obj).toMatch(/^v \s*[-\d.]+\s+[-\d.]+\s+[-\d.]+$/m);
	});

	it('should contain face data for buildings', async () => {
		const result = await exportToOBJ([makeBuilding()], null, testBounds);
		const obj = decodeOBJ(result);
		// Faces start with 'f '
		expect(obj).toMatch(/^f\s+\d+(\s+\d+)+$/m);
	});

	it('should contain object and group markers for buildings', async () => {
		const result = await exportToOBJ([makeBuilding()], null, testBounds);
		const obj = decodeOBJ(result);
		expect(obj).toContain('o Buildings');
		expect(obj).toContain('g building_1');
	});

	it('should handle empty objects array', async () => {
		const result = await exportToOBJ([], null, testBounds);
		const obj = decodeOBJ(result);
		expect(obj).toContain('o Buildings');
		// No vertex or face data
		expect(obj).not.toMatch(/^v /m);
	});

	it('should handle multiple buildings', async () => {
		const buildings = [makeBuilding(), makeBuilding()];
		const result = await exportToOBJ(buildings, null, testBounds);
		const obj = decodeOBJ(result);
		expect(obj).toContain('g building_1');
		expect(obj).toContain('g building_2');
	});

	it('should call progress callback', async () => {
		const progress: { percent: number; message: string }[] = [];
		await exportToOBJ([], null, testBounds, (info) => {
			progress.push({ percent: info.percent!, message: info.message! });
		});
		expect(progress.length).toBeGreaterThan(0);
		expect(progress[progress.length - 1].percent).toBe(100);
	});
});
