// OBJ exporter (Wavefront OBJ format)
// Universal 3D format that works in Rhino, Blender, and most 3D software

import type { Bounds, GeometryObject, ProgressCallback } from '../types';
import { extrudeBuildings } from '../geometry/buildings';
import { generateTerrainMesh } from '../elevation/terrain';
import { getMaxXY } from '../geometry/coordinates';
import * as m from '$lib/paraglide/messages';

/**
 * Export geometry objects and terrain to OBJ format
 * OBJ is universally supported by Rhino, Blender, and all major 3D software
 */
export async function exportTo3DM(
	objects: GeometryObject[],
	elevationMatrix: number[][] | null,
	bounds: Bounds,
	onProgress?: ProgressCallback
): Promise<Uint8Array> {
	notify(onProgress, 0, m.progress_dxf_init());

	// OBJ file header
	let obj = '# OBJ File Generated by swzpln\n';
	obj += '# https://swzpln.de / https://opencityplans.com\n';
	obj += '# Data (c) OpenStreetMap.org contributors\n\n';

	let vertexOffset = 1; // OBJ indices start at 1, not 0

	notify(onProgress, 10, 'Processing buildings...');

	// Generate terrain mesh first if available
	let terrainMesh = null;
	let gridSize = null;
	const maxXY = getMaxXY(bounds);

	if (elevationMatrix) {
		terrainMesh = generateTerrainMesh(elevationMatrix, bounds);
		gridSize = { rows: elevationMatrix.length, cols: elevationMatrix[0]?.length || 0 };
	}

	// Filter and process buildings
	const buildings = objects
		.filter((obj) => obj.type === 'building' && obj.buildingMetadata)
		.map(b => ({
			footprint: b.path,
			metadata: b.buildingMetadata!,
			id: undefined,
			relationId: b.relationId,
			isOutline: b.isOutline,
			holes: b.holes
		}));

	obj += `o Buildings\n`;

	// Process all buildings (grouped + terrain)
	const meshes = extrudeBuildings(buildings, terrainMesh || undefined, gridSize || undefined, maxXY);

	let processedCount = 0;
	for (const mesh of meshes) {
		obj += `\n# Building Group Part ${processedCount + 1}\n`;
		obj += `g building_${processedCount + 1}\n`;

		// Add vertices
		for (const v of mesh.vertices) {
			obj += `v ${v.x.toFixed(3)} ${v.y.toFixed(3)} ${v.z.toFixed(3)}\n`;
		}

		// Add faces (OBJ uses 1-based indexing)
		for (const face of mesh.faces) {
			if (face.length < 3) continue;
			obj += 'f';
			for (const idx of face) {
				obj += ` ${vertexOffset + idx}`;
			}
			obj += '\n';
		}

		vertexOffset += mesh.vertices.length;
		processedCount++;

		if (processedCount % 50 === 0) {
			notify(onProgress, 10 + Math.round((processedCount / meshes.length) * 60), `Exporting buildings: ${processedCount}/${meshes.length}`);
		}
	}

	// Export terrain if available
	if (terrainMesh) {
		notify(onProgress, 75, 'Adding terrain mesh...');

		obj += '\n# Terrain\n';
		obj += 'o Terrain\n';
		obj += 'g terrain\n';

		// Add terrain vertices
		terrainMesh.vertices.forEach((v) => {
			obj += `v ${v.x.toFixed(3)} ${v.y.toFixed(3)} ${v.z.toFixed(3)}\n`;
		});

		// Add terrain faces (triangles)
		for (let i = 0; i < terrainMesh.triangles.length; i += 3) {
			const v1 = vertexOffset + terrainMesh.triangles[i];
			const v2 = vertexOffset + terrainMesh.triangles[i + 1];
			const v3 = vertexOffset + terrainMesh.triangles[i + 2];
			obj += `f ${v1} ${v2} ${v3}\n`;
		}
	}

	notify(onProgress, 100, 'OBJ export complete');

	// Convert to Uint8Array
	const encoder = new TextEncoder();
	return encoder.encode(obj);
}

function notify(cb: ProgressCallback | undefined, percent: number, message: string) {
	if (cb) cb({ step: 'export', percent, message });
}
